# This file contains defaults for the "config" object used in the Snakefile.
# To temporarily override or provide a value, you can use snakemake's --config
# or --configfile options.
---
s3_staging_url: s3://nextstrain-staging
slack_webhook: ~
sequences: "data/sequences.fasta"
metadata: "data/metadata.tsv"
local_sequences: "<path to your loacl sequences.fasta>"
local_gisaid_metadata: "<path to your local metadata tsv in gisaid format>"
